const PAYMENT_FLOW_TYPES = {
  REGISTER: "REGISTER",
  GUEST: "GUEST",
};

const PAYMENT_REQUEST_TYPES = {
  HOSTED_CHECKOUT: "HOSTED_CHECKOUT",
  LINK_DE_PAGO: "LINK_DE_PAGO",
  SUBSCRIPTION: "SUBSCRIPTION",
};

module.exports = { PAYMENT_FLOW_TYPES, PAYMENT_REQUEST_TYPES };
